version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app

  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - backend
      - frontend
    restart: always

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./Frontend:/app