version: '3'
services:
  backend:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
  
  frontend:
    platform: linux/amd64
    build:
      dockerfile: Dockerfile
      context: ./Frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./Frontend:/app