version: '3'
services:
  backend:
    image: andrewmulya/peoplecounter-backend
    ports:
      - "8000:8000"
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    image: andrewmulya/peoplecounter-nginx
    ports:
      - "3050:80"
    volumes:
  frontend:
    image: andrewmulya/peoplecounter-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./Frontend:/app