name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker images
      run: |
        docker build -t andrewmulya/peoplecounter-backend ./Backend
        docker build -t andrewmulya/peoplecounter-frontend ./Frontend
        docker build -t andrewmulya/peoplecounter-nginx ./nginx
    - name: Push the Docker images
      run: |
        docker push andrewmulya/peoplecounter-backend:latest
        docker push andrewmulya/peoplecounter-frontend:latest
        docker push andrewmulya/peoplecounter-nginx:latest
